[project]
name = "aac-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "pyyaml>=6.0.3",
    "streamlit>=1.52.2",
]
